### PR TITLE
fix(src/Element.ts) Element type error

### PR DESCRIPTION
**Pull request by lzxb**
Detail see: #724

### CODE REVIEW

**Comment by pissang** [comment]
Thanks! Seems `getInsideTextFill` and `getOutsideFill` also needs this change.

**Comment by lzxb** [comment]
I tested it. No

**Comment by lzxb** [comment]
I use it to develop a real-time chart, which is very good

**Comment by pissang** [comment]
I mean these methods are similar in design. Their returns should all be nullable.

**Comment by lzxb** [comment]
I see you. Subclass inheritance can be reset to `undefined`

**Pull request closed without merging**
