### PR TITLE
fix: avoid errors when executing unfinished operations after dispose

### PR DESCRIPTION
**Pull request by yechunxi**
A chart is performing certain operations. After the operation, it will be refreshed and calling flush. At this time, the instance has been disposed, an error will appear. such this [issue](https://github.com/ecomfe/zrender/issues/904) and in react native echart [issue](https://github.com/wuba/react-native-echarts/issues/92)

### CODE REVIEW

**Comment by zhiqingchen** [comment]
@plainheart Can you review this pr?

**Comment by yechunxi** [comment]
> Thanks for your contribution! I would prefer adding a flag `_disposed` and checking it before invoking the instance methods, as ECharts does.
> 
> https://github.com/apache/echarts/blob/master/src/core/echarts.ts#L1168-L1185

Thank you, your suggestion will be better. Based on the suggestions you gave me, I implemented it again. I hope to review it

**Comment by yechunxi** [comment]
> Thanks for your contribution! I would prefer adding a flag `_disposed` and checking it before invoking the instance methods, as ECharts does.
> 
> https://github.com/apache/echarts/blob/master/src/core/echarts.ts#L1168-L1185

**Review by plainheart — APPROVED** [review]

**Comment by AkshayPathakMLF** [comment]
@plainheart Are you able to release a new version since this has been merged in?

**Pull request merged**
