### PR TITLE
change: the judge of the cpx and cpy

### PR DESCRIPTION
**Pull request by HCLacids**

### CODE REVIEW

**Comment by pissang** [comment]
@HCLacids Can you describe the reason to do this change?

**Comment by HCLacids** [comment]
> @HCLacids Can you describe the reason to do this change?

Because it turns to NaN, not null in the echarts when the self-pointed Node needs four nodes to render the edge. If I change the value of the cpx2 and cpy2, it will make the label out of control.

**Comment by pissang** [comment]
@HCLacids I'm afraid it will also ignore the 0 value.

**Comment by HCLacids** [comment]
> @HCLacids I'm afraid it will also ignore the 0 value.

How about "cpx2 == null || cpy == nul || cpx2 == NaN || cpy == NaN" or "cpx2 == NaN || cpy2 == NaN"

**Comment by pissang** [comment]
Also I think it's a problem in echarts. We should avoid fixing it by changing the design of underlying zrender

**Comment by HCLacids** [comment]
> Also I think it's a problem in echarts. We should avoid fixing it by changing the design of underlying zrender. Especially it's a breaking change

But in the BezierCurve class in zrender, the cpy2 and cpx2 are only the number type, not the null type

**Pull request closed without merging**
