### PR TITLE
fix(env): fix env detection compatibility in node v21.1.0

### PR DESCRIPTION
**Pull request by Uzlopak**
This PR improves the detection of nodejs version 21.1.0 and above

### CODE REVIEW

**Comment by Uzlopak** [comment]
I personally would have preferred

`if (typeof process !== 'undefined' && process.versions && typeof node.versions.node === 'string')`

**Review by plainheart — APPROVED** [review]
Thanks for your contribution!

Related information:
- Release note: https://github.com/nodejs/node/releases/tag/v21.1.0
- PR: https://github.com/nodejs/node/pull/50200

**Comment by plainheart** [comment]
@Uzlopak A small question: Before v21.1.0, is the `navigator.userAgent` undefined? Will it bring an NPE? Do we need to add the existence check?

**Comment by Uzlopak** [comment]
For what stands the abbreviation NPE?

**Comment by plainheart** [comment]
Null Pointer Exception - that is, a type error thrown when accessing properties / methods of an undefined object.

**Comment by plainheart** [comment]
I looked through the [release note of Node v21.0.0](https://github.com/nodejs/node/releases/tag/v21.0.0), which added the `navigator.hardwareConcurrency` property. So in that version, `navigator.userAgent` may be undefined.

**Comment by Uzlopak** [comment]
In node 21.0.0 userAgent was missing. But node 21 is anyway a dev version and it was expected to result in regressions. So using it for production is anyway bad.

I would personally try to detect node/deno/bun with

`if ((typeof process !== 'undefined' && typeof process.version === 'string') || 'Deno' in window)`

first one would detect node and bun, second one would detect Deno.

**Comment by tniessen** [comment]
> But node 21 is anyway a dev version and it was expected to result in regressions. So using it for production is anyway bad.

FWIW, that is _not_ the official stance of the Node.js project. While we generally recommend LTS versions for production, non-LTS release lines are not "dev versions". They typically receive the same level of support as LTS versions, albeit for a shorter amount of time. Breaking changes may be introduced in both LTS and non-LTS release lines, but regressions are highly undesirable in any case.

**Pull request merged**
