### PR TITLE
fix(env): fix env detection compatibility for node, bun, and deno

### PR DESCRIPTION
**Pull request by Uzlopak**
@plainheart 

As discussed.

### CODE REVIEW

**Comment by sannajammeh** [comment]
#1046 related. Any progress on this?

**Comment by Uzlopak** [comment]
Well what progress do you expect when there is no feedback?

**Comment by sannajammeh** [comment]
There has been no new release in 4 months, although PRs are being merged no release has been made. @plainheart SSR is broken in Node 21 for apache echarts.

**Comment by plainheart** [comment]
@sannajammeh The fixes in PR #1036 should make it work for Node.js >= v21.1.0. As for the new release, we are preparing for Apache ECharts v5.5.0, the process will hopefully be done later this month.

**Comment by bangbang93** [comment]
4-month past. Any schedule for this?

**Review by plainheart — APPROVED** [review]

**Pull request merged**
